const { Hybrid } = require("../type");

const hybridData = [
  {
    hybrid_name: "Fusion Hybrid",
    engine_type: "I-4",
    transmission: "automatic",
    color: "black",
    price: 28000.0,
  },
  {
    hybrid_name: "Fusion Hybrid",
    engine_type: "I-4",
    transmission: "automatic",
    color: "silver",
    price: 28000.0,
  },
  {
    hybrid_name: "Fusion Hybrid",
    engine_type: "I-4",
    transmission: "automatic",
    color: "blue",
    price: 28000.0,
  },
  {
    hybrid_name: "Fusion Hybrid",
    engine_type: "I-4",
    transmission: "automatic",
    color: "red",
    price: 28000.0,
  },
  {
    hybrid_name: "Fusion Hybrid",
    engine_type: "I-4",
    transmission: "automatic",
    color: "white",
    price: 28000.0,
  },
  {
    hybrid_name: "Fusion Plug-In Hybrid",
    engine_type: "I-4",
    transmission: "automatic",
    color: "black",
    price: 35000.0,
  },
  {
    hybrid_name: "Fusion Plug-In Hybrid",
    engine_type: "I-4",
    transmission: "automatic",
    color: "silver",
    price: 35000.0,
  },
  {
    hybrid_name: "Fusion Plug-In Hybrid",
    engine_type: "I-4",
    transmission: "automatic",
    color: "blue",
    price: 35000.0,
  },
  {
    hybrid_name: "Fusion Plug-In Hybrid",
    engine_type: "I-4",
    transmission: "automatic",
    color: "red",
    price: 35000.0,
  },
  {
    hybrid_name: "Fusion Plug-In Hybrid",
    engine_type: "I-4",
    transmission: "automatic",
    color: "white",
    price: 35000.0,
  },
  {
    hybrid_name: "Escape Hybrid",
    engine_type: "I-4",
    transmission: "automatic",
    color: "black",
    price: 28030.0,
  },
  {
    hybrid_name: "Escape Hybrid",
    engine_type: "I-4",
    transmission: "automatic",
    color: "silver",
    price: 28030.0,
  },
  {
    hybrid_name: "Escape Hybrid",
    engine_type: "I-4",
    transmission: "automatic",
    color: "blue",
    price: 28030.0,
  },
  {
    hybrid_name: "Escape Hybrid",
    engine_type: "I-4",
    transmission: "automatic",
    color: "red",
    price: 28030.0,
  },
  {
    hybrid_name: "Escape Hybrid",
    engine_type: "I-4",
    transmission: "automatic",
    color: "white",
    price: 28030.0,
  },
  {
    hybrid_name: "Escape Plug-In Hybrid",
    engine_type: "I-4",
    transmission: "automatic",
    color: "black",
    price: 33075.0,
  },
  {
    hybrid_name: "Escape Plug-In Hybrid",
    engine_type: "I-4",
    transmission: "automatic",
    color: "silver",
    price: 33075.0,
  },
  {
    hybrid_name: "Escape Plug-In Hybrid",
    engine_type: "I-4",
    transmission: "automatic",
    color: "blue",
    price: 33075.0,
  },
  {
    hybrid_name: "Escape Plug-In Hybrid",
    engine_type: "I-4",
    transmission: "automatic",
    color: "red",
    price: 33075.0,
  },
  {
    hybrid_name: "Escape Plug-In Hybrid",
    engine_type: "I-4",
    transmission: "automatic",
    color: "white",
    price: 33075.0,
  },
  {
    hybrid_name: "Mustang Mach-E",
    engine_type: "I-4",
    transmission: "automatic",
    color: "black",
    price: 42895.0,
  },
  {
    hybrid_name: "Mustang Mach-E",
    engine_type: "I-4",
    transmission: "automatic",
    color: "silver",
    price: 42895.0,
  },
  {
    hybrid_name: "Mustang Mach-E",
    engine_type: "I-4",
    transmission: "automatic",
    color: "blue",
    price: 42895.0,
  },
  {
    hybrid_name: "Mustang Mach-E",
    engine_type: "I-4",
    transmission: "automatic",
    color: "red",
    price: 42895.0,
  },
  {
    hybrid_name: "Mustang Mach-E",
    engine_type: "I-4",
    transmission: "automatic",
    color: "white",
    price: 42895.0,
  },
  {
    hybrid_name: "Explorer",
    engine_type: "I-4",
    transmission: "automatic",
    color: "black",
    price: 32675.0,
  },
  {
    hybrid_name: "Explorer",
    engine_type: "I-4",
    transmission: "automatic",
    color: "silver",
    price: 32675.0,
  },
  {
    hybrid_name: "Explorer",
    engine_type: "I-4",
    transmission: "automatic",
    color: "blue",
    price: 32675.0,
  },
  {
    hybrid_name: "Explorer",
    engine_type: "I-4",
    transmission: "automatic",
    color: "red",
    price: 32675.0,
  },
  {
    hybrid_name: "Explorer",
    engine_type: "I-4",
    transmission: "automatic",
    color: "white",
    price: 32675.0,
  },
  {
    hybrid_name: "F-150 Lightning",
    engine_type: "I-4",
    transmission: "automatic",
    color: "black",
    price: 39974.0,
  },
  {
    hybrid_name: "F-150 Lightning",
    engine_type: "I-4",
    transmission: "automatic",
    color: "silver",
    price: 39974.0,
  },
  {
    hybrid_name: "F-150 Lightning",
    engine_type: "I-4",
    transmission: "automatic",
    color: "blue",
    price: 39974.0,
  },
  {
    hybrid_name: "F-150 Lightning",
    engine_type: "I-4",
    transmission: "automatic",
    color: "red",
    price: 39974.0,
  },
  {
    hybrid_name: "F-150 Lightning",
    engine_type: "I-4",
    transmission: "automatic",
    color: "white",
    price: 39974.0,
  },
];

const seedHybrids = () => Hybrid.bulkCreate(hybridData);

module.exports = seedHybrids;
