const { Sedan } = require("../model");

const sedanData = [
  {
    sedan_name: "Fusion",
    engine_type: "2.5L i-VCT",
    transmission: "automatic",
    color: "black",
    price: 23170.0,
  },
  {
    sedan_name: "Fusion",
    engine_type: "2.5L i-VCT",
    transmission: "automatic",
    color: "silver",
    price: 23170.0,
  },
  {
    sedan_name: "Fusion",
    engine_type: "2.5L i-VCT",
    transmission: "automatic",
    color: "blue",
    price: 23170.0,
  },
  {
    sedan_name: "Fusion",
    engine_type: "2.5L i-VCT",
    transmission: "automatic",
    color: "red",
    price: 23170.0,
  },
  {
    sedan_name: "Fusion",
    engine_type: "2.5L i-VCT",
    transmission: "automatic",
    color: "white",
    price: 23170.0,
  },
  {
    sedan_name: "Mustang Fastback",
    engine_type: "2.3L EcoBoost",
    transmission: "automatic",
    color: "black",
    price: 27155.0,
  },
  {
    sedan_name: "Mustang Fastback",
    engine_type: "2.3L EcoBoost",
    transmission: "automatic",
    color: "silver",
    price: 27155.0,
  },
  {
    sedan_name: "Mustang Fastback",
    engine_type: "2.3L EcoBoost",
    transmission: "automatic",
    color: "blue",
    price: 27155.0,
  },
  {
    sedan_name: "Mustang Fastback",
    engine_type: "2.3L EcoBoost",
    transmission: "automatic",
    color: "red",
    price: 27155.0,
  },
  {
    sedan_name: "Mustang Fastback",
    engine_type: "2.3L EcoBoost",
    transmission: "automatic",
    color: "white",
    price: 27155.0,
  },
  {
    sedan_name: "Mustang Convertible",
    engine_type: "2.3L EcoBoost",
    transmission: "automatic",
    color: "black",
    price: 32655.0,
  },
  {
    sedan_name: "Mustang Convertible",
    engine_type: "2.3L EcoBoost",
    transmission: "automatic",
    color: "silver",
    price: 32655.0,
  },
  {
    sedan_name: "Mustang Convertible",
    engine_type: "2.3L EcoBoost",
    transmission: "automatic",
    color: "blue",
    price: 32655.0,
  },
  {
    sedan_name: "Mustang Convertible",
    engine_type: "2.3L EcoBoost",
    transmission: "automatic",
    color: "red",
    price: 32655.0,
  },
  {
    sedan_name: "Mustang Convertible",
    engine_type: "2.3L EcoBoost",
    transmission: "automatic",
    color: "white",
    price: 32655.0,
  },
  {
    sedan_name: "Mustang Mach 1",
    engine_type: "v8",
    transmission: "automatic",
    color: "black",
    price: 52720.0,
  },
  {
    sedan_name: "Mustang Mach 1",
    engine_type: "v8",
    transmission: "automatic",
    color: "silver",
    price: 52720.0,
  },
  {
    sedan_name: "Mustang Mach 1",
    engine_type: "v8",
    transmission: "automatic",
    color: "blue",
    price: 52720.0,
  },
  {
    sedan_name: "Mustang Mach 1",
    engine_type: "v8",
    transmission: "automatic",
    color: "red",
    price: 52720.0,
  },
  {
    sedan_name: "Mustang Mach 1",
    engine_type: "v8",
    transmission: "automatic",
    color: "white",
    price: 52720.0,
  },
  {
    sedan_name: "Mustang Shelby GT500",
    engine_type: "v8",
    transmission: "automatic",
    color: "black",
    price: 72900.0,
  },
  {
    sedan_name: "Mustang Shelby GT500",
    engine_type: "v8",
    transmission: "automatic",
    color: "silver",
    price: 72900.0,
  },
  {
    sedan_name: "Mustang Shelby GT500",
    engine_type: "v8",
    transmission: "automatic",
    color: "blue",
    price: 72900.0,
  },
  {
    sedan_name: "Mustang Shelby GT500",
    engine_type: "v8",
    transmission: "automatic",
    color: "red",
    price: 72900.0,
  },
  {
    sedan_name: "Mustang Shelby GT500",
    engine_type: "v8",
    transmission: "automatic",
    color: "white",
    price: 72900.0,
  },
];

const seedSedans = () => Sedan.bulkCreate(sedanData);

module.exports = seedSedans;
