const { Truck } = require("../type");

const truckData = [
  {
    truck_name: "F-150",
    engine_type: "v6",
    transmission: "automatic",
    color: "black",
    price: 28940.0,
  },
  {
    truck_name: "F-150",
    engine_type: "v6",
    transmission: "automatic",
    color: "silver",
    price: 28940.0,
  },
  {
    truck_name: "F-150",
    engine_type: "v6",
    transmission: "automatic",
    color: "blue",
    price: 28940.0,
  },
  {
    truck_name: "F-150",
    engine_type: "v6",
    transmission: "automatic",
    color: "red",
    price: 28940.0,
  },
  {
    truck_name: "F-150",
    engine_type: "v6",
    transmission: "automatic",
    color: "white",
    price: 28940.0,
  },
  {
    truck_name: "F-150",
    engine_type: "v8",
    transmission: "automatic",
    color: "black",
    price: 56330.0,
  },
  {
    truck_name: "F-150",
    engine_type: "v8",
    transmission: "automatic",
    color: "silver",
    price: 56330.0,
  },
  {
    truck_name: "F-150",
    engine_type: "v8",
    transmission: "automatic",
    color: "blue",
    price: 56330.0,
  },
  {
    truck_name: "F-150",
    engine_type: "v8",
    transmission: "automatic",
    color: "red",
    price: 56330.0,
  },
  {
    truck_name: "F-150",
    engine_type: "v8",
    transmission: "automatic",
    color: "white",
    price: 56330.0,
  },
  {
    truck_name: "Ranger",
    engine_type: "2.3L Ecoboost",
    transmission: "automatic",
    color: "black",
    price: 24820.0,
  },
  {
    truck_name: "Ranger",
    engine_type: "2.3L Ecoboost",
    transmission: "automatic",
    color: "silver",
    price: 24820.0,
  },
  {
    truck_name: "Ranger",
    engine_type: "2.3L Ecoboost",
    transmission: "automatic",
    color: "blue",
    price: 24820.0,
  },
  {
    truck_name: "Ranger",
    engine_type: "2.3L Ecoboost",
    transmission: "automatic",
    color: "red",
    price: 24820.0,
  },
  {
    truck_name: "Ranger",
    engine_type: "2.3L Ecoboost",
    transmission: "automatic",
    color: "white",
    price: 24820.0,
  },
  {
    truck_name: "F-250 XL",
    engine_type: "v8",
    transmission: "automatic",
    color: "black",
    price: 34230.0,
  },
  {
    truck_name: "F-250 XL",
    engine_type: "v8",
    transmission: "automatic",
    color: "silver",
    price: 34230.0,
  },
  {
    truck_name: "F-250 XL",
    engine_type: "v8",
    transmission: "automatic",
    color: "blue",
    price: 34230.0,
  },
  {
    truck_name: "F-250 XL",
    engine_type: "v8",
    transmission: "automatic",
    color: "red",
    price: 34230.0,
  },
  {
    truck_name: "F-250 XL",
    engine_type: "v8",
    transmission: "automatic",
    color: "white",
    price: 34230.0,
  },
  {
    truck_name: "F-350 XL",
    engine_type: "v8",
    transmission: "automatic",
    color: "black",
    price: 35745.0,
  },
  {
    truck_name: "F-350 XL",
    engine_type: "v8",
    transmission: "automatic",
    color: "silver",
    price: 35745.0,
  },
  {
    truck_name: "F-350 XL",
    engine_type: "v8",
    transmission: "automatic",
    color: "blue",
    price: 35745.0,
  },
  {
    truck_name: "F-350 XL",
    engine_type: "v8",
    transmission: "automatic",
    color: "red",
    price: 35745.0,
  },
  {
    truck_name: "F-350 XL",
    engine_type: "v8",
    transmission: "automatic",
    color: "white",
    price: 35745.0,
  },
  {
    truck_name: "F-450 XL",
    engine_type: "v8",
    transmission: "automatic",
    color: "black",
    price: 50410.0,
  },
  {
    truck_name: "F-450 XL",
    engine_type: "v8",
    transmission: "automatic",
    color: "silver",
    price: 50410.0,
  },
  {
    truck_name: "F-450 XL",
    engine_type: "v8",
    transmission: "automatic",
    color: "blue",
    price: 50410.0,
  },
  {
    truck_name: "F-450 XL",
    engine_type: "v8",
    transmission: "automatic",
    color: "red",
    price: 50410.0,
  },
  {
    truck_name: "F-450 XL",
    engine_type: "v8",
    transmission: "automatic",
    color: "white",
    price: 50410.0,
  },
];

const seedTrucks = () => Truck.bulkCreate(truckData);

module.exports = seedTrucks;
